"""Optional parameters must keep their documentation.

An optional parameter generated by FastAPI/Pydantic is emitted as
``{"anyOf": [{...}, {"type": "null"}], "description": ..., "title": ...}``.
The description and title sit on the wrapper, not on the variant, so unwrapping
the union has to carry them through the way the ``$ref`` branch already does.
"""

import pytest

from cuga.backend.tools_env.registry.mcp_manager.openapi_parser import SimpleOpenAPIParser

pytestmark = pytest.mark.unit


def _parser() -> SimpleOpenAPIParser:
    return SimpleOpenAPIParser({"openapi": "3.0.0", "info": {"title": "t", "version": "1"}, "paths": {}})


def test_optional_primitive_keeps_wrapper_description_and_title():
    parsed = _parser()._parse_schema(
        {
            "anyOf": [{"type": "string"}, {"type": "null"}],
            "description": "Days to repeat on.",
            "title": "Repeat Days",
        }
    )

    assert parsed.description == "Days to repeat on."
    assert parsed.title == "Repeat Days"
    assert parsed.type == "string"
    assert parsed.nullable is True


def test_optional_variant_description_survives_when_wrapper_has_none():
    parsed = _parser()._parse_schema(
        {"anyOf": [{"type": "integer", "description": "inner"}, {"type": "null"}]}
    )

    assert parsed.description == "inner"


def test_wrapper_description_outranks_the_variant():
    parsed = _parser()._parse_schema(
        {
            "anyOf": [{"type": "integer", "description": "inner"}, {"type": "null"}],
            "description": "outer",
        }
    )

    assert parsed.description == "outer"


def test_multi_variant_union_keeps_wrapper_description():
    parsed = _parser()._parse_schema(
        {
            "anyOf": [{"type": "number"}, {"type": "string"}, {"type": "null"}],
            "description": "A figure or its label.",
            "title": "Answer",
        }
    )

    assert parsed.description == "A figure or its label."
    assert parsed.title == "Answer"
