#!/bin/bash
# ============================================================
# Step 2 — Deploy the ONE CUGA-events app to Code Engine.
#
#  1. (re)create a CE secret from deploy/ce/.env.ce  (LLM + channel tokens).
#  2. create the app: --port 7860, single always-warm instance, events env.
#  3. read the public route, set EVENTS_PUBLIC_URL to it (2nd revision), and write
#     deploy/ce/.ce_urls.env.
#
# Idempotent: re-running deletes + recreates the app (clean env/secret refresh).
# The app name — hence the URL — is stable across delete/recreate.
# ============================================================
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}/config.sh"
admin_guard "${1:-}"
require_login
ce_target

if [[ ! -f "$ENV_CE_FILE" ]]; then
  echo "Missing $ENV_CE_FILE — generate it from your local .env first:"
  echo "   ./make_env_ce.sh"
  exit 1
fi

# ---- 1. CE secret from .env.ce (create or replace) --------------------------
echo "== syncing secret '$SECRET_NAME' from $(basename "$ENV_CE_FILE") =="
if ibmcloud ce secret get -n "$SECRET_NAME" >/dev/null 2>&1; then
  ibmcloud ce secret update --name "$SECRET_NAME" --from-env-file "$ENV_CE_FILE" >/dev/null
else
  ibmcloud ce secret create --name "$SECRET_NAME" --from-env-file "$ENV_CE_FILE" >/dev/null
fi

# ---- 2. app env (non-secret; secrets ride in via --env-from-secret) ---------
DEPLOY_REV="$(date +%s)"
args=(
  --image "$IMAGE_REF"
  --registry-secret "$REGISTRY_SECRET_NAME"
  --port "$APP_PORT"
  --min-scale "$MIN_SCALE" --max-scale "$MAX_SCALE"
  --cpu "$CPU" --memory "$MEMORY" --ephemeral-storage "$EPHEMERAL"
  --request-timeout "$REQUEST_TIMEOUT"
  --env-from-secret "$SECRET_NAME"
  --env "EVENTS_WORKER_BACKEND=cuga"
  --env "EVENTS_SCHEDULER=$EVENTS_SCHEDULER"
  --env "EVENTS_TELEGRAM_BACKEND=$EVENTS_TELEGRAM_BACKEND"
  --env "EVENTS_DISCORD_BACKEND=$EVENTS_DISCORD_BACKEND"
  --env "EVENTS_SLACK_BACKEND=$EVENTS_SLACK_BACKEND"
  --env "EVENTS_DISCORD_MEMBERS_INTENT=1"
  --env "MCP_SERVERS_FILE=$MCP_SERVERS_FILE_IN_IMAGE"
  --env "DEPLOY_REV=$DEPLOY_REV"
)
# Agent model: classic generalist by default; supervisor + roster when opted in.
if [[ "$CE_EVENTS_SUPERVISOR" == "1" ]]; then
  args+=( --env "EVENTS_SUPERVISOR=1" --env "EVENTS_SUPERVISOR_ROSTER=$CE_ROSTER" )
  echo "   agent model: SUPERVISOR (roster=$CE_ROSTER)"
else
  echo "   agent model: CLASSIC generalist (set CE_EVENTS_SUPERVISOR=1 to use a roster)"
fi

if ibmcloud ce app get -n "$APP_NAME" >/dev/null 2>&1; then
  echo "Deleting existing app '$APP_NAME' for a clean redeploy ..."
  ibmcloud ce app delete --name "$APP_NAME" --force --wait --ignore-not-found
fi
echo "== creating app '$APP_NAME' =="
ibmcloud ce app create --name "$APP_NAME" "${args[@]}"

# ---- 3. public URL -> EVENTS_PUBLIC_URL (so Slack/OAuth self-URLs resolve) ---
URL=$(ibmcloud ce app get --name "$APP_NAME" --output url)
echo "== setting EVENTS_PUBLIC_URL=$URL =="
ibmcloud ce app update --name "$APP_NAME" --env "EVENTS_PUBLIC_URL=$URL" >/dev/null

echo "# Generated by deploy/ce/2_deploy_app.sh" > "$URLS_ENV_FILE"
echo "export CUGA_CE_URL=\"$URL\"" >> "$URLS_ENV_FILE"

cat <<EOF

===================================================
 CUGA events is live (no Activepieces):
   $URL
   Studio:      $URL/manage   (→ Studio tab)
   Capability:  $URL/api/events/status

 Auto-armed at boot (direct backends): web · Telegram · Discord
 Slack — ONE manual step (CE route replaces the tunnel):
   Slack app → Event Subscriptions → Request URL:
     $URL/api/events/slack/events
   (SLACK_SIGNING_SECRET is already in the secret.)

 Smoke test:   python deploy/ce/3_smoke.py
===================================================
EOF
