"""
CugaLite package initialization.

This module provides utilities to ensure that model replies are returned
in their entirety without unintended truncation.
"""

from __future__ import annotations

__all__ = ["process_model_reply"]


def process_model_reply(reply: str) -> str:
    """
    Return the complete model reply.

    Historically, CugaLite mistakenly returned only the first sentence of a
    model's output by splitting on punctuation. This function now returns the
    full, trimmed reply, preserving all sentences and line breaks.

    Parameters
    ----------
    reply: str
        The raw text generated by the model.

    Returns
    -------
    str
        The full, unmodified reply with surrounding whitespace removed.
    """
    if not isinstance(reply, str):
        raise TypeError(f"Expected a string for reply, got {type(reply)!r}")

    # Strip leading/trailing whitespace but keep the internal content intact.
    return reply.strip()