name: 💡 Use Case / Success Story
description: Share how you're using CUGA or showcase a successful implementation
title: "[Use Case]: "
labels: ["use-case", "community"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear about how you're using CUGA! Share your use case, success story, or interesting implementation to inspire others in the community.

  - type: textarea
    id: use-case-title
    attributes:
      label: Use Case Title
      description: Give your use case a descriptive title
      placeholder: |
        Example: "Automated Customer Service Agent for E-commerce Platform"
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Provide a high-level overview of what you built or how you're using CUGA
      placeholder: |
        Example: Built an AI agent that handles customer inquiries, processes returns, and manages order status updates across multiple e-commerce platforms using CUGA's multi-tool integration.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category best describes your use case?
      options:
        - Business Automation
        - Data Processing & Analytics
        - Customer Service & Support
        - Content Creation & Management
        - Development & DevOps
        - Research & Education
        - Personal Productivity
        - Integration & Workflow
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Problem Solved
      description: What problem did CUGA help you solve?
      placeholder: |
        Example: Our customer service team was overwhelmed with repetitive inquiries about order status, returns, and product information. Manual processing was taking 2-3 hours per day.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: How did you implement your solution? What tools and integrations did you use?
      placeholder: |
        Example: 
        - Used OpenAPI tools to connect to Shopify and WooCommerce APIs
        - Integrated MCP filesystem tools for order document management  
        - Created LangChain tools for email response generation
        - Set up automated workflows using CUGA's task orchestration
    validations:
      required: true

  - type: textarea
    id: tools-used
    attributes:
      label: Tools & Technologies Used
      description: List the specific tools, APIs, and technologies you integrated with CUGA
      placeholder: |
        Example:
        - CUGA Agent with browser automation
        - OpenAPI integrations: Shopify API, Stripe API
        - MCP tools: Filesystem, Database connector
        - LangChain tools: Custom email generator, sentiment analysis
        - Additional: SendGrid for email, Slack for notifications
    validations:
      required: true

  - type: textarea
    id: results
    attributes:
      label: Results & Impact
      description: What results did you achieve? Include metrics, time saved, or other benefits if possible.
      placeholder: |
        Example:
        - Reduced customer response time from 4 hours to 15 minutes
        - Automated 80% of routine customer inquiries
        - Saved 15+ hours per week of manual work
        - Improved customer satisfaction scores by 25%
    validations:
      required: true

  - type: textarea
    id: challenges
    attributes:
      label: Challenges & Solutions
      description: What challenges did you face during implementation and how did you solve them?
      placeholder: |
        Example:
        - Challenge: API rate limiting with high-volume requests
        - Solution: Implemented request batching and retry logic with exponential backoff
        
        - Challenge: Handling complex multi-step workflows
        - Solution: Used CUGA's task decomposition to break complex requests into manageable steps
    validations:
      required: false

  - type: textarea
    id: code-snippets
    attributes:
      label: Code Snippets / Configuration
      description: Share relevant code snippets, configuration files, or architecture diagrams (remove sensitive information)
      placeholder: |
        ```python
        # Example configuration or key code snippets
        from cuga import CugaAgent
        
        agent = CugaAgent()
        # Your implementation details...
        ```
        
        ```yaml
        # mcp_servers.yaml example
        services:
          - shopify_api:
              url: https://your-shop.myshopify.com/admin/api/openapi.json
        ```
    validations:
      required: false

  - type: textarea
    id: lessons-learned
    attributes:
      label: Lessons Learned / Tips
      description: What did you learn during the implementation? Any tips for others attempting similar use cases?
      placeholder: |
        Example:
        - Start with simple workflows and gradually add complexity
        - Test tool integrations individually before combining them
        - Use dummy data during development to avoid API rate limits
        - Monitor agent performance and add fallback mechanisms
    validations:
      required: false

  - type: dropdown
    id: scale
    attributes:
      label: Scale of Implementation
      description: What's the scale of your implementation?
      options:
        - Personal project / Prototype
        - Small team (2-10 users)
        - Department (10-50 users)
        - Company-wide (50+ users)
        - Production system with external users
    validations:
      required: true

  - type: checkboxes
    id: sharing-permissions
    attributes:
      label: Sharing Permissions
      description: How can the community use this information?
      options:
        - label: This use case can be featured in CUGA documentation or blog posts
          required: false
        - label: I'm open to being contacted for follow-up questions about this implementation
          required: false
        - label: I'm willing to share more detailed implementation guidance with the community
          required: false
        - label: This implementation is open source and available for others to use
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, links to demos, blog posts, or repositories?
      placeholder: |
        Links to:
        - Demo videos or screenshots
        - Blog posts about your implementation
        - Open source repositories
        - Company case studies
        - Performance metrics or dashboards
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have removed any sensitive information from my submission
          required: true
        - label: I am sharing this use case to help and inspire the CUGA community
          required: true
        - label: The information provided is accurate and represents my actual experience
          required: true
