#!/usr/bin/env python
"""Render events_docs/verification.html from events_docs/verification_data.json.

The data file is written by the harnesses themselves (tests/events/_ledger.py) — every proving run
refreshes its own cells, so a cell's date is the date that capability was last actually verified.
Cells with no record render as UNPROVEN. Never hand-edit verification.html; add evidence by
running a harness (or, for human-action rows, via a one-line `record(...)`).

    python scripts/gen_ledger.py
"""

from __future__ import annotations

import html
import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "events_docs" / "verification_data.json"
OUT = ROOT / "events_docs" / "verification.html"

# The matrix shape: (section, surface key, display, [capability columns])
INTEGRATIONS = [
    ("github", "GitHub (14 triggers)"), ("box", "Box (3 triggers)"),
    ("gmail", "Gmail (4 triggers)"), ("slack", "Slack watchers (8)"),
    ("discord", "Discord watchers (2)"), ("telegram", "Telegram watcher (1)"),
    ("webhook", "Webhook (pinned + routed)"),
]
PLATFORM = [
    ("cron", "CRON (real schedule ticks)"), ("poll", "POLL (real interval ticks)"),
    ("channels", "Channels chat (web·Slack·Discord·Telegram)"),
    ("nlflow", "NL→Flow (the compiler)"), ("delegation", "Supervisor routing"),
    ("offline", "Offline invariants (make test)"),
]
CAPS = [("arm", "Arm"), ("fire_synth", "Fire — synthetic"), ("fire_real", "Fire — real event")]
BADGE = {"ok": ("✓", "ok"), "partial": ("◐", "part"), "blocked": ("✗", "no")}


def _cell(rec) -> str:
    if not rec:
        return '<td class="dim">— unproven</td>'
    sym, cls = BADGE.get(rec["verdict"], ("?", "dim"))
    note = html.escape(rec.get("note") or "")
    return (f'<td><span class="{cls}">{sym} {rec["date"][:10]}</span>'
            f'<div class="how">{note} <i>({html.escape(rec.get("source", ""))})</i></div></td>')


def main() -> int:
    data = json.load(open(DATA)) if DATA.exists() else {"records": {}}
    R = data["records"]

    def row(key, label, caps):
        cells = "".join(_cell(R.get(f"{key}::{c}")) for c, _ in caps)
        return f"<tr><td><b>{html.escape(label)}</b></td>{cells}</tr>"

    integ = "".join(row(k, lbl, CAPS) for k, lbl in INTEGRATIONS)
    plat = "".join(row(k, lbl, [("arm", ""), ("fire_real", "")]) for k, lbl in PLATFORM)
    OUT.write_text(f"""<!DOCTYPE html>
<!-- GENERATED by scripts/gen_ledger.py from verification_data.json — do not hand-edit.
     Evidence is written by the harnesses (tests/events/_ledger.py). -->
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Verification ledger — what is PROVEN, per integration</title>
<style>
  :root {{ --ink:#1a1d26; --dim:#6b7386; --line:#e3e6ee; --acc:#0f62fe; --ok:#24a148;
          --warn:#b28600; --bad:#da1e28; --card:#f6f7fa; --code:#eef1f6; }}
  * {{ box-sizing: border-box; }}
  body {{ margin: 0 auto; max-width: 68rem; padding: 3rem 1.5rem 6rem; color: var(--ink);
         font: 15px/1.55 -apple-system, "IBM Plex Sans", Segoe UI, sans-serif; }}
  h1 {{ font-size: 1.9rem; margin: 0 0 .3em; }} h2 {{ font-size: 1.3rem; margin: 1.8em 0 .4em; }}
  .lead {{ font-size: 1.08rem; color: var(--dim); }}
  code {{ background: var(--code); border-radius: 4px; padding: .08em .3em; font-size: .88em; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th {{ text-align: left; font-size: .74rem; text-transform: uppercase; letter-spacing: .06em;
       color: var(--dim); }}
  th, td {{ padding: .5rem .7rem; border-bottom: 1px solid var(--line); vertical-align: top; }}
  .ok {{ color: var(--ok); font-weight: 700; }} .part {{ color: var(--warn); font-weight: 700; }}
  .no {{ color: var(--bad); font-weight: 700; }} .dim {{ color: var(--dim); }}
  .how {{ color: var(--dim); font-size: .84em; margin-top: 2px; }}
  .note {{ border-left: 4px solid var(--acc); background: var(--card); padding: .8rem 1.1rem;
          border-radius: 0 8px 8px 0; margin: 1rem 0; }}
  .foot {{ margin-top: 2.5rem; color: var(--dim); font-size: .9rem;
          border-top: 1px solid var(--line); padding-top: 1rem; }}
</style></head>
<body>
<h1>Verification ledger</h1>
<p class="lead">Auto-generated evidence: each cell shows the date a capability was <b>last
actually proven</b> by a harness run — plus how. Cells no harness has proven say so.</p>
<div class="note"><b>Vocabulary.</b> <span class="ok">✓</span> proven on that date ·
<span class="part">◐</span> partially proven / blocked on the noted action ·
<span class="no">✗</span> impossible by design (noted) · <b>Fire—synthetic</b> = provider-exact
payload through the REAL armed flow · <b>Fire—real event</b> = the provider itself emitted it.
ARMED alone is never sold as working.</div>
<h2>Integrations (PUSH)</h2>
<table><tr><th>Integration</th><th>Arm</th><th>Fire — synthetic</th><th>Fire — real event</th></tr>
{integ}</table>
<h2>Flow kinds &amp; platform</h2>
<table><tr><th>Surface</th><th>Arm / gate</th><th>Fire / result</th></tr>
{plat}</table>
<div class="foot">Rendered {time.strftime("%Y-%m-%d %H:%M")} from
<code>verification_data.json</code> · automated report: <code>results/index.html</code> ·
method: <a href="TESTING.md">TESTING.md</a>. A fresh harness run refreshes its own cells.</div>
</body></html>
""")
    print(f"✓ wrote verification.html — {len(R)} evidence records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
