from typing import Any, Protocol


class RelationalStore(Protocol):
    def execute(self, sql: str, params: tuple = ()) -> None: ...
    def fetchall(self, sql: str, params: tuple = ()) -> list: ...
    def fetchone(self, sql: str, params: tuple = ()) -> Any: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...
