#!/bin/bash
# ============================================================
# Generate events/deploy/.env.ce (the CE secret source) from your local .env, copying
# ONLY the allow-listed keys the no-AP events app needs. The output is gitignored
# and chmod 600. No secret is ever printed.
#
#   ./make_env_ce.sh              # from ../../.env
#   SRC=/path/to/.env ./make_env_ce.sh
# ============================================================
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SRC="${SRC:-$SCRIPT_DIR/../../.env}"
OUT="$SCRIPT_DIR/.env.ce"

[[ -f "$SRC" ]] || { echo "No source env at $SRC (set SRC=/path/to/.env)"; exit 1; }

# The allow-list — model profile + LLM creds + gateway + the four channels.
# NOTHING Activepieces. AGENT_SETTING_CONFIG picks the model profile
# (settings.watsonx.toml); without it CUGA falls back to settings.openai.toml
# and crashes on a missing OPENAI_API_KEY.
KEYS=(
  AGENT_SETTING_CONFIG
  WATSONX_APIKEY WATSONX_URL WATSONX_PROJECT_ID WATSONX_SPACE_ID
  OPENAI_API_KEY
  LLM_PROVIDER LLM_MODEL
  GATEWAY_TOKEN
  TELEGRAM_BOT_TOKEN EVENTS_TELEGRAM_BOT_USERNAME
  DISCORD_BOT_TOKEN
  SLACK_BOT_TOKEN SLACK_SIGNING_SECRET
  EVENTS_WEBHOOK_KEY
)

umask 177                       # -> 600 on the output
: > "$OUT"
echo "# Generated by make_env_ce.sh from $SRC — DO NOT COMMIT." >> "$OUT"
copied=(); skipped=()
for k in "${KEYS[@]}"; do
  line=$(grep -E "^$k=" "$SRC" | tail -1 || true)
  val=${line#*=}
  # strip surrounding quotes + inline comments + whitespace
  val=$(printf '%s' "$val" | sed -e 's/[[:space:]]*#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//')
  if [[ -n "$val" ]]; then echo "$k=$val" >> "$OUT"; copied+=("$k"); else skipped+=("$k"); fi
done

# The agent config store shares the events database, so UI-created agents survive an instance
# replace. Derived rather than asked for: EVENTS_DB is already the managed Postgres DSN, and a
# second copy in .env would be one more thing to keep in sync. 2_deploy.sh only turns
# storage.mode=prod on when this key made it into the secret, so an events DB on SQLite (no DSN)
# simply leaves the config store local instead of deploying something that cannot boot.
db=$(grep -E "^EVENTS_DB=" "$OUT" | tail -1 | cut -d= -f2-)
case "$db" in
  postgres://*|postgresql://*)
    echo "DYNACONF_STORAGE__POSTGRES_URL=$db" >> "$OUT"
    copied+=("DYNACONF_STORAGE__POSTGRES_URL")
    ;;
esac

echo "wrote $OUT (chmod 600)"
echo "  copied  : ${copied[*]}"
echo "  skipped : ${skipped[*]:-none} (absent/empty in $SRC)"
echo ""
echo "Next:  CUGA_CE_ADMIN=1 ./2_deploy.sh"
