#!/bin/bash
# ============================================================
# Generate events/deploy/.env.ce (the CE secret source) from your local .env, copying
# ONLY the allow-listed keys the no-AP events app needs. The output is gitignored
# and chmod 600. No secret is ever printed.
#
#   ./make_env_ce.sh              # from ../../.env
#   SRC=/path/to/.env ./make_env_ce.sh
#
# WHY THIS MERGES RATHER THAN REWRITES
# ------------------------------------
# Two kinds of key end up in this file and only one of them lives in .env:
#
#   COPIED     model profile, LLM creds, gateway token, channel tokens, the events secrets.
#              Yours, in .env, same values you develop against.
#   PROVISIONED  the managed-database DSN and its CA. Created in the CLOUD by ./4_postgres.sh.
#              They are NOT in .env — and for EVENTS_DB the local copy is actively WRONG
#              (it points at localhost:5432, so copying it would aim Code Engine at its own
#              empty container).
#
# This script used to open with `: > "$OUT"`, truncating. So it wrote the copied keys and
# silently dropped every provisioned one. That is invisible until the next time the secret is
# CREATED rather than updated — after `teardown.sh WIPE_SECRET=1`, or in a fresh project —
# because `secret update` merges and hides the loss. Then the deploy comes up with no DSN
# (ephemeral SQLite, every armed flow lost on the next pod replace), no CA (a verify-full DSN
# cannot connect) and no webhook key (the endpoint 401s everything), and still exits 0.
#
# So provisioned keys are CARRIED FORWARD from the existing .env.ce, and 4_postgres.sh writes
# them here as well as into the live secret. Deleting .env.ce is now the only way to lose them,
# and 2_deploy.sh refuses to deploy without them.
# ============================================================
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SRC="${SRC:-$SCRIPT_DIR/../../.env}"
OUT="$SCRIPT_DIR/.env.ce"

[[ -f "$SRC" ]] || { echo "No source env at $SRC (set SRC=/path/to/.env)"; exit 1; }

# ---- COPIED from .env ------------------------------------------------------
# Model profile + LLM creds + gateway + the events secrets + the four channels.
# NOTHING Activepieces. AGENT_SETTING_CONFIG picks the model profile
# (settings.watsonx.toml); without it CUGA falls back to settings.openai.toml
# and crashes on a missing OPENAI_API_KEY.
KEYS=(
  AGENT_SETTING_CONFIG
  WATSONX_APIKEY WATSONX_URL WATSONX_PROJECT_ID WATSONX_SPACE_ID
  OPENAI_API_KEY
  LLM_PROVIDER LLM_MODEL
  GATEWAY_TOKEN
  # The events-layer secrets. Every gate they guard FAILS CLOSED, so an omission here is not a
  # weaker deployment — it is a broken one. EVENTS_WEBHOOK_KEY unset means POST
  # /api/events/hook/<name> refuses every request; CUGA_SECRET_KEY unset means admin-entered
  # OAuth secrets are stored in plaintext.
  EVENTS_WEBHOOK_KEY
  CUGA_SECRET_KEY
  TELEGRAM_BOT_TOKEN EVENTS_TELEGRAM_BOT_USERNAME
  DISCORD_BOT_TOKEN
  SLACK_BOT_TOKEN SLACK_SIGNING_SECRET
  WHATSAPP_TOKEN WHATSAPP_PHONE_NUMBER_ID WHATSAPP_APP_SECRET WHATSAPP_VERIFY_TOKEN
)

# ---- PROVISIONED in the cloud, carried forward -----------------------------
# Written by ./4_postgres.sh. Never read from .env — see the header.
CLOUD_KEYS=(
  EVENTS_DB
  EVENTS_DB_CA_B64
)

# Read one key's value out of an env file: last assignment wins, quotes and
# trailing comments stripped. Prints nothing when absent.
read_key() {
  local key="$1" file="$2" line val
  [[ -f "$file" ]] || return 0
  line=$(grep -E "^$key=" "$file" | tail -1 || true)
  [[ -n "$line" ]] || return 0
  val=${line#*=}
  printf '%s' "$val" | sed -e 's/[[:space:]]*#.*//' -e 's/^[[:space:]]*//' \
                           -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//'
}

umask 177                       # -> 600 on the output
TMP="$OUT.tmp.$$"
trap 'rm -f "$TMP"' EXIT
: > "$TMP"
echo "# Generated by make_env_ce.sh from $SRC — DO NOT COMMIT." >> "$TMP"

copied=(); skipped=(); carried=(); lost=()
for k in "${KEYS[@]}"; do
  val=$(read_key "$k" "$SRC")
  if [[ -n "$val" ]]; then echo "$k=$val" >> "$TMP"; copied+=("$k"); else skipped+=("$k"); fi
done
for k in "${CLOUD_KEYS[@]}"; do
  val=$(read_key "$k" "$OUT")           # from the PREVIOUS .env.ce, not from .env
  if [[ -n "$val" ]]; then echo "$k=$val" >> "$TMP"; carried+=("$k"); else lost+=("$k"); fi
done

# The agent config store shares the events database, so UI-created agents survive an instance
# replace. Derived rather than asked for: EVENTS_DB is already the managed Postgres DSN, and a
# second copy in .env would be one more thing to keep in sync. 2_deploy.sh only turns
# storage.mode=prod on when this key made it into the secret, so an events DB on SQLite (no DSN)
# simply leaves the config store local instead of deploying something that cannot boot.
db=$(read_key EVENTS_DB "$TMP")
case "$db" in
  postgres://*|postgresql://*)
    echo "DYNACONF_STORAGE__POSTGRES_URL=$db" >> "$TMP"
    carried+=("DYNACONF_STORAGE__POSTGRES_URL")
    ;;
esac

mv "$TMP" "$OUT"
trap - EXIT

echo "wrote $OUT (chmod 600)"
echo "  copied from .env : ${copied[*]}"
echo "  skipped          : ${skipped[*]:-none} (absent/empty in $SRC)"
echo "  carried forward  : ${carried[*]:-none} (provisioned in the cloud)"
if (( ${#lost[@]} )); then
  echo ""
  echo "  ⚠ MISSING, and NOT recoverable from .env: ${lost[*]}"
  echo "    These are provisioned by ./4_postgres.sh, which writes them both here and into the"
  echo "    Code Engine secret. Without them a from-scratch deploy falls back to ephemeral SQLite"
  echo "    (armed flows lost on every pod replace) or cannot open a verify-full connection."
  echo "    Fix:  CUGA_CE_ADMIN=1 YES=1 ./4_postgres.sh     (idempotent — reuses the instance)"
fi
echo ""
echo "Next:  CUGA_CE_ADMIN=1 ./2_deploy.sh"
